# Generated by Django 4.1.1 on 2022-09-15 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_users_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='Name',
            new_name='Book',
        ),
    ]
