# Generated by Django 4.1.1 on 2022-09-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_name_books_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='Book',
            new_name='book',
        ),
    ]
