# Generated by Django 4.1.1 on 2022-09-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_book_books_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
